sc_common:
    resource: "@SCCommonBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

test_sc:
    resource: "@SCCommonBundle/Controller/"
    type:     annotation
    prefix:

student:
    type:     rest
    resource: SC\CommonBundle\Controller\StudentController
